name: autotests
on:

  #schedule:
   # - cron:  '*/50 *,* * * *'
    
  workflow_dispatch:
    inputs:
      arguments:
        required: false
        default: ""
        description: "pytest additional arguments, e.g. `-m simpletest`"


jobs:
  tests:
    runs-on: ubuntu-latest
    name: test
    env:
      SELENOID_BIN: $HOME/bin/cm
    strategy:
      matrix:
        browser: [remote_chrome]
    steps:
    - uses: actions/setup-python@v3
      with: { python-version: '3.9.7' }
    - run: mkdir -p $(dirname $SELENOID_BIN) && curl -s https://aerokube.com/cm/bash | bash && chmod +x ./cm && mv ./cm $SELENOID_BIN
    - uses: actions/checkout@v2
    - run: python3 -m pip install -r requirements.txt
    - run: $SELENOID_BIN selenoid configure --browsers chrome --last-versions 2
    - run: $SELENOID_BIN selenoid start
    #- run: pytest ${{github.event.inputs.arguments}} --bn ${{ matrix.browser }}
    - run: |
        if [ $GITHUB_EVENT_NAME = "schedule" ]; then
          export args="-m regression_prod --qase_enabled enable"
        else
          export args='${{github.event.inputs.arguments}}'
        fi
          pytest ${args} --bn ${{ matrix.browser }}
      env:
        SELENOID_URL: http://localhost:4444/wd/hub
        
  slack-workflow-status:
    if: failure()
    name: Post Workflow Status To Slack
    needs:
      - tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      with:
        status: ${{ job.status }}
      env:
        SLACK_WEBHOOK: https://hooks.slack.com/services/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
        SLACK_CHANNEL: tests_products_5-11
        SLACK_MESSAGE: Есть падение, капитан
